interface GlossoMdOptions {
  agentName: string;
  mode: string;
  network: string;
  primaryAddress: string;
  subWallets: Array<{
    index: number;
    label: string;
    address: string;
  }>;
  skills: string[];
}

/**
 * Generate a GLOSSO.md capability file.
 *
 * This file is designed to be read by both humans and LLMs.
 * It declares the wallet's capabilities so an agent knows
 * what operations it can perform.
 */
export function generateGlossoMd(options: GlossoMdOptions): string {
  const {
    agentName,
    mode,
    network,
    primaryAddress,
    subWallets,
    skills,
  } = options;

  const timestamp = new Date().toISOString();

  const allKnownSkills = [
    { name: 'glosso-wallet', description: 'Core wallet operations: balance, send, receive' },
    { name: 'glosso-pyth', description: 'Real-time price feeds via Pyth/Hermes' },
    { name: 'glosso-jupiter', description: 'Token swaps via Jupiter aggregator' },
    { name: 'glosso-staking', description: 'SOL staking and unstaking' },
    { name: 'glosso-nft', description: 'NFT minting and transfers' },
  ];

  const available = allKnownSkills.filter((s) => skills.includes(s.name));
  const unavailable = allKnownSkills.filter((s) => !skills.includes(s.name));

  const subWalletTable = subWallets
    .map((w) => `| ${w.index} | ${w.label} | \`${w.address}\` |`)
    .join('\n');

  const availableList = available.length
    ? available.map((s) => `- **${s.name}** — ${s.description}`).join('\n')
    : '- _None installed_';

  const unavailableList = unavailable.length
    ? unavailable.map((s) => `- **${s.name}** — ${s.description}`).join('\n')
    : '- _All skills installed_';

  const modeDescription: Record<string, string> = {
    sovereign: 'Self-custodial — keys encrypted on disk, no third-party dependency',
    privy: 'Privy embedded wallet — keys held in secure enclaves',
    turnkey: 'Turnkey infrastructure — keys in HSM, signed via API',
  };

  return `# GLOSSO.md — Agent Wallet Capability File

> Auto-generated by Glosso CLI on ${timestamp}
> This file declares the wallet capabilities available to this agent.

---

## Agent Identity

| Field | Value |
|---|---|
| Agent Name | ${agentName} |
| Wallet Mode | ${mode} |
| Mode Description | ${modeDescription[mode] || 'Unknown mode'} |
| Network | ${network} |
| Primary Address | \`${primaryAddress}\` |
| Provisioned At | ${timestamp} |

---

## Wallet Addresses

| Index | Label | Address |
|---|---|---|
${subWalletTable}

---

## Available Skills

Skills that are installed and ready to use:

${availableList}

---

## Unavailable Skills

Skills that are known but not yet installed:

${unavailableList}

---

## Wallet Operations

The following operations are available via the Glosso SDK:

### Core Operations (always available)
- \`wallet.getAddress(index?)\` — Get wallet address at index (default: 0)
- \`wallet.getBalance(index?)\` — Get SOL balance at index
- \`wallet.send(to, lamports, index?)\` — Send SOL to an address
- \`wallet.sign(transaction, index?)\` — Sign a transaction without broadcasting

### Usage Example
\`\`\`typescript
import { GlossoWallet } from '@glosso/sdk';

const wallet = new GlossoWallet();
const balance = await wallet.getBalance();
const sig = await wallet.send('recipient-address', 100_000);
\`\`\`

---

## Security Notes

- Private keys are **never** exposed in this file
- All addresses listed above are **public keys only**
- The wallet mode determines how signing is performed:
  - \`sovereign\`: Keys decrypted momentarily during signing, then discarded
  - \`privy\`: Signing delegated to Privy secure enclaves
  - \`turnkey\`: Signing performed by Turnkey HSM via API

---

_Generated by [Glosso](https://github.com/glosso) v0.1.0_
`;
}
